---
title: Bloem generator
hero_image: images/banner.png
description: Genereer bloemen om een achtergrondafbeelding of screensaver met een
  patroon te maken
duration: 2
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-10-18
steps:
- title: Inleiding
  completion: engaged
- title: Maak een bloem
- title: Maak een aangepast blok om bloemen te tekenen
- title: Personaliseer je bloemen
- title: 'Uitdaging: maak een bloemontwerp'
  challenge: true
- title: Sla je afbeeldingen op
- title: Willekeurige bloemgenerator
  completion: internal
- title: Bloem patronen
- title: 'Uitdaging: aangepaste bloemblokken'
  challenge: true
- title: Wat kun je verder nog doen?
