title: Flower generator
hero_image: images/banner.png
description: Generate flowers to create a patterned backdrop image or screensaver
theme: blue # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: true
ingredient: false
copyedit: true
curriculum: builder, design-1, programming-2, phys-comp-0, manufacture-0, community-0
interests: "art, art and design"
technologies: "scratch"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Generate a flower
  - title: Make a custom block to draw flowers
  - title: Customise your flowers
  - title: "Challenge: make a flower design"
  - title: Save the stage
  - title: "Challenge: random flower generator"
  - title: "Challenge: flower patterns"
  - title: "Challenge: custom flower blocks with inputs"
