---
title: Flower generator
hero_image: images/banner.png
description: Generate flowers to create a patterned backdrop image or screensaver
duration: 2
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-10-18
steps:
- title: Introduction
- title: Draw a flower
- title: Make a custom block to draw flowers
  completion:
  - engaged
- title: Customise your flowers
- title: 'Challenge: create a flower design'
  challenge: true
- title: Save your images
- title: Random flower generator
- title: Flower patterns
  completion:
  - internal
- title: 'Challenge: custom flower blocks'
  challenge: true
- title: What can you do now?
  completion:
  - external
