---
title: Flower generator
hero_image: images/banner.png
description: Generate flowers to create a patterned backdrop image or screensaver
duration: 2
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-10-18
steps:
- title: What you will make
- title: Draw a flower
  completion:
  - engaged
- title: Make a custom block 
- title: Custom colours
- title: Custom sizes and petals
- title: Save an image
- title: Random flower generator
  completion:
  - internal
- title: Challenge
  challenge: true
- title: What can you do now?
  completion:
  - external
