---
title: Генератор цветов
hero_image: images/banner.png
description: Генерируй цветы, чтобы создать изображение с узором, которое ты сможешь
  использовать как фон или заставку
duration: 2
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-10-18
steps:
- title: Введение
  completion: engaged
- title: Создание цветка
- title: Создай пользовательский блок, чтобы нарисовать цветы
- title: Отредактируй цветы
- title: 'Задача: создать цветочный рисунок'
  challenge: true
- title: Сохрани изображения
- title: Генератор случайных цветов
  completion: internal
- title: Цветочные узоры
- title: 'Задача: пользовательские блоки цветов'
  challenge: true
- title: Что дальше?
