---
title: Генератор цветов
hero_image: images/banner.png
description: Генерируй цветы, чтобы создать изображение с узором, которое ты сможешь использовать как фон или заставку
duration: 2
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-10-18
steps:
  - 
    title: Введение
  - 
    title: Создание цветка
  - 
    title: Создай пользовательский блок, чтобы нарисовать цветы
    completion:
      - engaged
  - 
    title: Отредактируй цветы
  - 
    title: 'Задача: создать цветочный рисунок'
    challenge: true
  - 
    title: Сохрани изображения
  - 
    title: Генератор случайных цветов
  - 
    title: Цветочные узоры
    completion:
      - internal
  - 
    title: 'Задача: пользовательские блоки цветов'
    challenge: true
  - 
    title: Что дальше?
