---
title: फूल जनरेटर
hero_image: images/banner.png
description: पैटर्न वाली बैकड्रॉप छवि या स्क्रीनसेवर बनाने के लिए फूल उत्पन्न करें I
duration: 2
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-10-18
steps:
  - title: "परिचय"
  - title: फूल उत्पन्न करें
  - title: फूल बनाने के लिए एक कस्टम ब्लॉक बनाएँ
  - title: अपने फूलों को अनुकूल करें
  - title: "चुनौती: एक फूल का डिज़ाइन बनाएँ"
    challenge: true
  - title: अपनी images को इकट्ठा करना
  - title: random फूल जनरेटर
  - title: फूल के पैटर्न
  - title: "चुनौती: कस्टम फूल ब्लॉक"
    challenge: true
  - title: 'चुनौती: अधिक रुकावटें!'
