---
title: 花朵生成器
hero_image: images/banner.png
description: 画出很多花，用来创建有图案的背景图或屏幕保护程序
duration: 2
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-10-18
steps:
  - 
    title: 介绍
  - 
    title: Generate a flower
  - 
    title: Make a custom block to draw flowers
  - 
    title: Customise your flowers
  - 
    title: "Challenge: create a flower design"
    challenge: true
  - 
    title: Save your images
  - 
    title: Random flower generator
  - 
    title: Flower patterns
  - 
    title: "Challenge: custom flower blocks"
    challenge: true
  - 
    title: 接下来呢？
