---
title: Generador de flores
hero_image: images/banner.png
description: Crea flores para crear un patron de imagen de fondo o un protector de pantalla
duration: 2
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-10-18
steps:
  - 
    title: Introducción
  - 
    title: Crea una flor
  - 
    title: Haz un bloque personalizado para dibujar flores
    completion:
      - engaged
  - 
    title: Personaliza tus flores
  - 
    title: 'Desafío: crea un diseño de flores'
    challenge: true
  - 
    title: Guarda tus imágenes
  - 
    title: Generador de flores aleatorio
  - 
    title: Patrones de flores
    completion:
      - internal
  - 
    title: 'Desafío: bloques de flores personalizados'
    challenge: true
  - 
    title: '¿Qué viene a continuación?'
