---
title: Generator rož
hero_image: images/banner.png
description: Ustvari rože, da ustvariš mozaično sliko ozadja ali ohranjevalnik zaslona
duration: 2
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-10-18
steps:
  - 
    title: Uvod
  - 
    title: Ustvari rožo
  - 
    title: Ustvari svoj blok za risanje rož
  - 
    title: Prilagodi svoje rože
  - 
    title: "Izziv: ustvari cvetlični aranžma"
    challenge: true
  - 
    title: Shrani svoje slike
  - 
    title: Naključni generator rož
  - 
    title: Vzorci rož
  - 
    title: "Izziv: po meri narejeni bloki za rože"
    challenge: true
  - 
    title: Kaj sledi?
