---
title: مولد الزهور
hero_image: images/banner.png
description: توليد الزهور لإنشاء صورة خلفية منقوشة أو شاشة توقف
duration: 2
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-10-18
steps:
  - title: المقدمة
  - title: توليد زهرة
  - title: إنشاء تعليمة برمجية مخصصة لرسم الزهور
  - title: مظاهر الزهور الخاصة بك
  - title: "التحدي: إنشاء تصميم للزهور"
    challenge: true
  - title: حفظ صورك
  - title: مولد زهور عشوائي
  - title: أنماط الزهور
  - title: "التحدي: تعليمة الزهور المخصصة"
    challenge: true
  - title: ماهو التالي؟
