---
title: مولد الزهور
hero_image: images/banner.png
description: توليد الزهور لإنشاء صورة خلفية منقوشة أو شاشة توقف
duration: 2
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-10-18
steps:
  - 
    title: المقدمة
  - 
    title: توليد زهرة
  - 
    title: Make a custom block to draw flowers
  - 
    title: Customise your flowers
  - 
    title: "Challenge: create a flower design"
    challenge: true
  - 
    title: Save your images
  - 
    title: Random flower generator
  - 
    title: Flower patterns
  - 
    title: "Challenge: custom flower blocks"
    challenge: true
  - 
    title: What next?
